version: '3.8'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    ports:
      - '3307:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../../server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8081:8081

# docker compose -p registers-mysql up -d
