version: '3.8'
services:
  backend:
    container_name:  ${NAME_BACKEND}
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-1.0.0}
    restart: always
    image: ${NAME_BACKEND}:${IMAGE_TAG}
    ports:
      - 8081:8081
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_BACKEND=${NAME_BACKEND}

  frontend:
    container_name: ${NAME_FRONTEND}
    build:
      context: ./client/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-1.0.0}      
    restart: always
    image: ${NAME_FRONTEND}:${IMAGE_TAG}
    ports:
      - 80:80
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_FRONTEND=${NAME_FRONTEND}
      
  phpmyadmin:
    container_name: ${PHP_MYADMIN}
    image: ${PHP_MYADMIN}:${IMAGE_TAG}
    restart: always
    environment:
      - PMA_HOST=192.168.225.111
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    ports:
      - 8082:80

# docker compose up -d
