version: '3.8'
services:
  backend:
    container_name:  ${NAME_BACKEND}
    build:
      context: ./server/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-1.0.0}
    restart: always
    image: ${NAME_BACKEND}:${IMAGE_TAG}
    ports:
      - 8081:8081
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_BACKEND=${NAME_BACKEND}

  frontend:
    container_name: ${NAME_FRONTEND}
    build:
      context: ./client/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-1.0.0}      
    restart: always
    image: ${NAME_FRONTEND}:${IMAGE_TAG}
    ports:
      - 80:80
    environment:
      - IMAGE_TAG=${IMAGE_TAG:-1.0.0}
      - NAME_FRONTEND=${NAME_FRONTEND}
####
  database:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-8.0}
    container_name: ${NAME_DATABASE}
    restart: always
    image: ${NAME_DATABASE}:${IMAGE_TAG}
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=Khoi@8888
      - IMAGE_TAG=${IMAGE_TAG:-8.0}
      - NAME_DATABASE=${NAME_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'

  phpmyadmin:
    build:
      context: ./phpmyadmin/
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG:-latest}
    container_name: ${NAME_PHPMYADMIN}
    restart: always
    image: ${NAME_PHPMYADMIN}:${IMAGE_TAG}
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=Khoi@8888
      - IMAGE_TAG=${IMAGE_TAG:-latest}
      - NAME_PHPMYADMIN=${NAME_PHPMYADMIN}
    ports:
      - 80:80

volumes:
    mysql_data:
# docker compose up -d
