version: "3.8"
services:
  nginx:
    env_file: ../../nginx/env
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ../../client/build:/usr/share/nginx/html
      - ../../nginx/nginx.conf:/etc/nginx/sites-available/{{ http_conf }}
    # docker compose -p registers-nginx up -d
