version: '3.8'
services:
  backend:
    build:
      context: ../server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081

  nginx:
    image: nginx:1.23.3
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ../client/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=192.168.225.111
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    ports:
      - 8082:80

# docker compose -p registers-pro up -d
