# Use the official phpMyAdmin image as a base
FROM phpmyadmin/phpmyadmin:latest

# Set environment variables
ENV PMA_HOST=database
ENV PMA_PORT=3306
ENV MYSQL_ROOT_PASSWORD=Khoi@8888

# Expose the phpMyAdmin port
EXPOSE 80
