version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'

  phpmyadmin:
    container_name: registers-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    ports:
      - 80:80
volumes:
    mysql_data:

#sudo docker compose -p up -d