CREATE DATABASE IF NOT EXISTS signup CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE signup;

CREATE TABLE IF NOT EXISTS login (
    id INT(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(120) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE USER 'root'@'192.168.225.110' IDENTIFIED WITH mysql_native_password BY 'Khoi@8888';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'192.168.225.110' WITH GRANT OPTION;

CREATE USER 'admin'@'%' IDENTIFIED BY 'Khoi@8888';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
