- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  become_method: sudo
  tasks:

    - name: Add host domain crelease.webapp.local  về IP server Nexus
      lineinfile:
        path: /etc/hosts   # Đường dẫn tới file host
        line: "192.168.225.102 crelease.webapp.local"

    - name: Log in to Nexus Docker registry
      docker_login:
        registry_url: "{{ NEXUS_URL }}"
        username: "{{ USER }}"
        password: "{{ PASS }}"

    # - name: Stop and remove existing backend container
    #   docker_container:
    #     name: "{{ NAME_BACKEND }}"
    #     state: absent
    #     force_kill: yes

    # - name: Stop and remove existing frontend container
    #   docker_container:
    #     name: "{{ NAME_FRONTEND }}"
    #     state: absent
    #     force_kill: yes

    # - name: Remove all Docker images
    #   shell: |
    #     docker rmi $(docker images -q) || true
    #   ignore_errors: yes

    - name: Get running containers
      docker_host_info:
        containers: yes
      register: docker_info

    - name: Stop running containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ docker_info.containers | map(attribute='Id') | list }}"
    - name: Remove Stoped docker containers
      shell: |
        docker rm $(docker ps -a -q);
      when: docker_info.containers != 0

    - name: Get details of all images
      docker_host_info:
        images: yes
        verbose_output: yes
      register: image_info
    - name: Remove all images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop: "{{ image_info.images | map(attribute='Id') | list }}"

    - name: Pull backend image from Nexus Repository
      docker_image:
        name: "{{ NEXUS_URL }}/{{ NAME_BACKEND }}"
        tag: "{{ IMAGE_TAG }}"
        source: pull

    - name: Pull frontend image from Nexus Repository
      docker_image:
        name: "{{ NEXUS_URL }}/{{ NAME_FRONTEND }}"
        tag: "{{ IMAGE_TAG }}"
        source: pull

    - name: Run new backend container
      docker_container:
        name: "{{ NAME_BACKEND }}"
        image: "{{ NEXUS_URL }}/{{ NAME_BACKEND }}:{{ IMAGE_TAG }}"
        state: started
        ports:
          - "8081:8081"

    - name: Run new frontend container
      docker_container:
        name: "{{ NAME_FRONTEND }}"
        image: "{{ NEXUS_URL }}/{{ NAME_FRONTEND }}:{{ IMAGE_TAG }}"
        state: started
        ports:
          - "80:80"

