- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  become_method: sudo
  tasks:

    # - name: Log in to Nexus Docker registry
    #   docker_login:
    #     registry_url: "{{ REGISTRY }}"
    #     username: "{{ USER }}"
    #     password: "{{ PASS }}"

    - name: Log in to Nexus Docker registry & Pull Docker image from Nexus
      docker_image:
        name: "{{ IMAGE_NAME }}"
        source: pull
        tag: "{{ TAG }}"
        registry_url: "{{ REGISTRY }}"
        username: "{{ USER }}"
        password: "{{ PASS }}"

    - name: Run Docker container
      docker_container:
        name: "{{ CONTAINER_NAME }}"
        image: "{{ IMAGE_NAME }}"
        state: started
        ports:
          - "80:300"
        volumes:
          - "/var/www/html"
