- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  become_method: sudo
  tasks:

    - name: Log in to Nexus Docker registry
      docker_login:
        registry_url: "{{ REGISTRY }}"
        username: "{{ USER }}"
        password: "{{ PASS }}"

    - name: Run Docker container
      docker_container:
        name: register
        image: "{{ REGISTRY }}/{{ IMAGE_NAME }}:{{ TAG }}"
        detach: yes  # Chạy container trong chế độ detach
        ports:
          - "80:3000"  # Chuyển tiếp cổng 80 của máy host sang cổng 80 của container
        state: started  # Chạy container

