version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
volumes:
    mysql_data:

#sudo docker compose -p register-mysql up -d