version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=signup
      - MYSQL_ROOT_PASSWORD=Khoi@8888
    ports:
      - '3307:3306'